Repository ashishsahu1/ML-ProjectYard, pull requests merged in 2021-03, with the labels that each got.

#70 Stock Price Prediction
  Stock Price Prediction/Dataset/testset.xls
  Stock Price Prediction/Dataset/trainset.xls
  Stock Price Prediction/Model/Stock_Price_Prediction.ipynb
  Stock Price Prediction/Model/stockprice.pkl
Labels: GSSOC21, Level2

#103 Cancer Prediction Model
  Cancer Prediction Model/Dataset/data.csv
  Cancer Prediction Model/Model/CancerPrediction.ipynb
  Cancer Prediction Model/Model/cancer prediction
Labels: GSSOC21, Level2

#107 Music Genre Classification Model
  Music Genre Classification/Music Genre Classification.ipynb
  Music Genre Classification/README.md
Labels: GSSOC21, Level2

#90 Twitter Sentiment Analysis
  Twitter Sentiment Analysis/Datasets/Twitter Sentiments.csv
  Twitter Sentiment Analysis/Datasets/testdata.manual.2009.06.14.csv
Labels: GSSOC21, Level2

#93 Issue#78 : Diabetes Prediction
  Diabetes Predictor/Dataset/About.md
  Diabetes Predictor/Dataset/diabetes.csv
  Diabetes Predictor/Model/Diabetespred.ipynb
  Diabetes Predictor/Model/model.sav
  Diabetes Predictor/Readme.md
Labels: GSSOC21, Level2

#113 Handwritten Digit Recognition Model (Issue #14)
  Handwritten Digit Recognition/Dataset/mnist.h5
  Handwritten Digit Recognition/Model/gui_digit_recognizer.py
  Handwritten Digit Recognition/Model/train_digit_recognizer.py
  Handwritten Digit Recognition/README.md
Labels: GSSOC21, Level2

#87 Football best 11
  FIFA playing 11/Dataset/FullData.csv
  FIFA playing 11/Model/Football_analysis.ipynb
Labels: GSSOC21, Level1

#141 Fertilizer Prediction Model
  Fertilizer Prediction Model/Dataset/Fertilizer.csv
  Fertilizer Prediction Model/Dataset/FertilizerData.csv
  Fertilizer Prediction Model/Model/Final_recommendationdata_creation.ipynb
  Fertilizer Prediction Model/Model/RandomForest.pkl
  Fertilizer Prediction Model/Model/XGBoost.pkl
Labels: GSSOC21, Level2

#151 Issue 120
  Speech Recognition System/Readme.md
  Speech Recognition System/Speech.py
  Speech Recognition System/requirements.txt
Labels: GSSOC21, Level2

#126 Successfully Predicted Quality Of Wine Using SVR
  WineQualityTest/Wine_Quality.py
  WineQualityTest/winequality-white.csv
  exit
Labels: GSSOC21, Level1

#161 Loan Prediction
  Loan Prediction/Dataset/test.csv
  Loan Prediction/Dataset/train.csv
  Loan Prediction/Model/Loan_Prediction.ipynb
  Loan Prediction/Model/Readme.md
  Loan Prediction/Model/app.py
  Loan Prediction/Model/model.pkl
Labels: GSSOC21, Level3

#169 update contributing.md
  CONTRIBUTING.md
Labels: GSSOC21, Level1

#213 Resolving issue #207 : Add Twitch Streamer's Analysis
  Twitch Streamers Analysis/Dataset/about.md
  Twitch Streamers Analysis/Dataset/twitchdata-update.csv
  Twitch Streamers Analysis/Model/TwitchTopStreamersAnalysis.ipynb
Labels: GSSOC21, Level2

#229 Added Imagenet classification
  Imagenet classification/DataSet/Link.txt
  Imagenet classification/Image_Classifier.ipynb
  Imagenet classification/README.md
  Imagenet classification/app.py
  Imagenet classification/images/1.jpg
  Imagenet classification/images/ss.png
  Imagenet classification/images/turtle_PNG69.png
  Imagenet classification/static/css/main.css
  Imagenet classification/static/js/main.js
  Imagenet classification/templates/base.html
  Imagenet classification/templates/index.html
Labels: GSSOC21, Level3
