Repository ashishsahu1/ML-ProjectYard, pull requests merged in 2021-04, with the labels that each got.

#269 Added Car brand classification
  Car Brand Classification/Datasets.zip
  Car Brand Classification/Lambo.png
  Car Brand Classification/Procfile
  Car Brand Classification/README.md
  Car Brand Classification/Transfer Learning Resnet 50.ipynb
  Car Brand Classification/app.py
  Car Brand Classification/requirements.txt
  Car Brand Classification/static/css/main.css
  Car Brand Classification/static/js/main.js
  Car Brand Classification/templates/base.html
  Car Brand Classification/templates/index.html
Labels: GSSOC21, Level3

#257 GNN Classification
  Classification using GNN/dataset_classification_using_GNN.ipynb
Labels: GSSOC21, Level2

#284 Colorful-Sketch Filter
  Colorful sketch filter/Colorful-Sketch Filter.py
  Colorful sketch filter/Photos/(Colorful-Sketch Filtered)image.jpg
  Colorful sketch filter/Photos/image.jpg
  Colorful sketch filter/README.md
Labels: Assigned, Level2

#268 issue-228
  Pneumonia Predictor/Dataset/dataset.txt
  Pneumonia Predictor/Model/PneumoniaDetection.ipynb
Labels: GSSOC21, Level2

#300 Added code and pkl file in drive
  Plant Disease Detection/Dataset/About.md
  Plant Disease Detection/Model/label_transform.pkl
  Plant Disease Detection/Model/plant_disease_detection.ipynb
  Plant Disease Detection/Readme.md
Labels: GSSOC21, Level2

#286 Addition of Time Series Forecasting of Active Covid 19 cases
  Time series forecasting covid 19 case/Time series forecasting covid 19 case.ipynb
Labels: GSSOC21, Level2

#293 Added Cotton Disease prediction
  Cotton-Disease-Prediction/Leaf_Prediction.png
  Cotton-Disease-Prediction/Procfile
  Cotton-Disease-Prediction/README.md
  Cotton-Disease-Prediction/Transfer Learning resnet152V2.ipynb
  Cotton-Disease-Prediction/app.py
  Cotton-Disease-Prediction/requirements.txt
  Cotton-Disease-Prediction/static/css/main.css
  Cotton-Disease-Prediction/static/js/main.js
  Cotton-Disease-Prediction/templates/base.html
  Cotton-Disease-Prediction/templates/index.html
  Cotton-Disease-Prediction/uploads/d_40_iaip.jpg
  Cotton-Disease-Prediction/uploads/dis_leaf_324_iaip.jpg
  Cotton-Disease-Prediction/uploads/dis_leaf_328_iaip.jpg
  Cotton-Disease-Prediction/uploads/dis_leaf_7_iaip.jpg
Labels: GSSOC21, Level3

#329 Mask detection using EfficientnetB3
  Recognition using EfficientNetB3/Face Mask detector.ipynb
  Recognition using EfficientNetB3/Mask.png
  Recognition using EfficientNetB3/README.md
  Recognition using EfficientNetB3/face mask detection- mtcnn.png
  Recognition using EfficientNetB3/face_detector.py
Labels: GSSOC21, Level2

#334 Resolving issue #287 : Added Room Classifier
  Room Classifier/Data/dataset.md
  Room Classifier/Deployment/Clean_Messsy_app.ipynb
  Room Classifier/Deployment/app.py
  Room Classifier/Deployment/deployment.md
  Room Classifier/Deployment/nohup .out
  Room Classifier/Model/Model_Vgg19.ipynb
  Room Classifier/Readme.md
  Room Classifier/Results/clean_result.PNG
  Room Classifier/Results/clean_result1.PNG
Labels: GSSOC21, Level3

#328 Android App for text classification
  Text based ML Android app Template/AndroidApp/MLAppTemplate/.gitignore
  Text based ML Android app Template/AndroidApp/MLAppTemplate/.idea/.gitignore
  Text based ML Android app Template/AndroidApp/MLAppTemplate/.idea/aws.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/.idea/codeStyles/Project.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/.idea/codeStyles/codeStyleConfig.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/.idea/compiler.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/.idea/gradle.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/.idea/jarRepositories.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/.idea/misc.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/.idea/uiDesigner.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/.gitignore
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/build.gradle
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/proguard-rules.pro
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/androidTest/java/com/example/mlapptemplate/ExampleInstrumentedTest.java
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/AndroidManifest.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/java/com/example/mlapptemplate/ApiHandler/ApiController.java
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/java/com/example/mlapptemplate/ApiHandler/ApiServiceProvider.java
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/java/com/example/mlapptemplate/MainActivity.java
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/drawable/ic_launcher_background.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/layout/activity_main.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/values/colors.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/values/strings.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/main/res/values/styles.xml
  Text based ML Android app Template/AndroidApp/MLAppTemplate/app/src/test/java/com/example/mlapptemplate/ExampleUnitTest.java
  Text based ML Android app Template/AndroidApp/MLAppTemplate/build.gradle
  Text based ML Android app Template/AndroidApp/MLAppTemplate/gradle.properties
  Text based ML Android app Template/AndroidApp/MLAppTemplate/gradle/wrapper/gradle-wrapper.jar
  Text based ML Android app Template/AndroidApp/MLAppTemplate/gradle/wrapper/gradle-wrapper.properties
  Text based ML Android app Template/AndroidApp/MLAppTemplate/gradlew
  Text based ML Android app Template/AndroidApp/MLAppTemplate/gradlew.bat
  Text based ML Android app Template/AndroidApp/MLAppTemplate/settings.gradle
  Text based ML Android app Template/Python Api Template/ML_App_API_template.ipynb
  Text based ML Android app Template/readme.md
Labels: GSSOC21, Level2

#332 Body Posture Correction Project added
  Body Posture Correction Project/README.md
  Body Posture Correction Project/alert.wav
  Body Posture Correction Project/images/ss1.png
  Body Posture Correction Project/images/ss2.png
  Body Posture Correction Project/index.html
  Body Posture Correction Project/style.css
  Body Posture Correction Project/video.js
Labels: GSSOC21

#360 Added files for maze solver
  Maze solver/Dataset/maze1.png
  Maze solver/Dataset/maze2.png
  Maze solver/Dataset/maze3.jpeg
  Maze solver/Dataset/maze4.png
  Maze solver/Dataset/maze5.png
  Maze solver/Model/maze_solver.ipynb
  Maze solver/README.md
Labels: GSSOC21, Level2
