Repository ashishsahu1/ML-ProjectYard, pull requests merged in 2021-05, with the labels that each got.

#397 Added 'E-Mail Classification' Project
  E-Mail Classification/Dataset/email.csv
  E-Mail Classification/Model/E-Mail Classification.ipynb
  E-Mail Classification/Model/E-MailClassification.pkl
  E-Mail Classification/README.md
Labels: GSSOC21, Level2

#394 Insurance cost prediction using Linear Regression
  Insurance cost prediction using linear regression/Dataset/About.md
  Insurance cost prediction using linear regression/Dataset/insurance_data.csv
  Insurance cost prediction using linear regression/Model/Insurance_Cost_Prediciton.ipynb
  Insurance cost prediction using linear regression/Model/linear_regression.pkl
  Insurance cost prediction using linear regression/Readme.md
Labels: GSSOC21, Level2

#382 Added 'Amazon Alexa Reviews Analysis' Project
  Amazon Alexa Reviews Analysis/Dataset/amazon_alexa.csv
  Amazon Alexa Reviews Analysis/Model/AmazonAlexaReviewsAnalysis.pkl
  Amazon Alexa Reviews Analysis/Model/Amazon_Alexa_Reviews_Analysis.ipynb
  Amazon Alexa Reviews Analysis/README.md
Labels: GSSOC21, Level2

#383 Gesture Volume Control
  Gesture Volume Control/Model/VolumeControl.py
  Gesture Volume Control/Model/handModule.py
  Gesture Volume Control/README.md
  Gesture Volume Control/__pycache__/handModule.cpython-39.pyc
Labels: GSSOC21, Level2

#370 Fix issue #359 Improve Weather Forecasting
  Weather Forecasting/Model/Improved-Weather-Forecast.ipynb
Labels: GSSOC21, Level1

#404 Added Face Detection using Yolov3
  Face Detection using YoloV3/README.md
  Face Detection using YoloV3/assets/outside_000001_yoloface.jpg
  Face Detection using YoloV3/assets/yolo-architecture.png
  Face Detection using YoloV3/cfg/face.names
  Face Detection using YoloV3/cfg/face_classes.txt
  Face Detection using YoloV3/cfg/yolo_anchors.txt
  Face Detection using YoloV3/cfg/yolov3-face.cfg
  Face Detection using YoloV3/model-weights/get_models.sh
  Face Detection using YoloV3/requirements.txt
  Face Detection using YoloV3/samples/meeting_11_304.jpg
  Face Detection using YoloV3/samples/outside_000001.jpg
  Face Detection using YoloV3/scripts/run_yolo_face_image.sh
  Face Detection using YoloV3/yolo/model.py
  Face Detection using YoloV3/yolo/yolo.py
  Face Detection using YoloV3/yoloface.py
Labels: GSSOC21, Level2

#368 Faical Lock System
  facial_lock_system/Model/face_data_collection.py
  facial_lock_system/Model/face_lock_data_training_and_prediction.py
  facial_lock_system/Model/faced_lock_application.py
  facial_lock_system/dataset/haarcascade_frontalface_default.xml
  facial_lock_system/readme.md
  facial_lock_system/requirements.text
Labels: GSSOC21, Level2

#406 Salary Predictor Web App #362
  Salary Predictor/Dataset/cleaned_dataset.csv
  Salary Predictor/Images/Capture_1.PNG
  Salary Predictor/Images/Capture_2.PNG
  Salary Predictor/Images/Capture_3.PNG
  Salary Predictor/Images/Capture_4.PNG
  Salary Predictor/Model/Model.ipynb
  Salary Predictor/Model/model_columns.pkl
  Salary Predictor/Model/random_forest1_model.sav
  Salary Predictor/README.md
  Salary Predictor/Server/__pycache__/app.cpython-38.pyc
  Salary Predictor/Server/app.py
  Salary Predictor/Server/models/model_columns.pkl
  Salary Predictor/Server/models/random_forest1_model.sav
  Salary Predictor/Server/templates/index.html
Labels: GSSOC21, Level3

#451 Update README.md
  README.md
Labels: GSSOC21, Level0

#418 Template for Connecting your ML model to amazon Alexa
  ML_Template_For_Amazon_alexa_connection/App/alexa_app.py
  ML_Template_For_Amazon_alexa_connection/Model/Model.py
  ML_Template_For_Amazon_alexa_connection/Readme.md
  ML_Template_For_Amazon_alexa_connection/__init__.py
  ML_Template_For_Amazon_alexa_connection/requirements.text
Labels: GSSOC21, Level2

#475 Detect parkinsons Disease
  Predict Parkinsons Disease/Dataset/About.md
  Predict Parkinsons Disease/Dataset/parkinsons.data
  Predict Parkinsons Disease/Model/Detect Parkinson.ipynb
  Predict Parkinsons Disease/Model/ParkinsonDetection.pkl
  Predict Parkinsons Disease/Readme.md
Labels: GSSOC21, Level1

#371 Issue-364: Added Jupyter, readme and sample images files used in hole detection
  Hole_Detection/Hole_Detection.ipynb
  Hole_Detection/Input Images/sample1.jpg
  Hole_Detection/Input Images/sample2.jpg
  Hole_Detection/Input Images/sample3.jpg
  Hole_Detection/Output Images/sample1.PNG
  Hole_Detection/Output Images/sample2.PNG
  Hole_Detection/Output Images/sample3.PNG
  Hole_Detection/README.md
Labels: GSSOC21, Level2

#479 Eid Festival Filter #477
  Eid Festival Filter/Code.py
  Eid Festival Filter/Images/Eid Festival Filtered Image.png
  Eid Festival Filter/Images/Image.jpg
  Eid Festival Filter/Images/eid.png
  Eid Festival Filter/README.md
Labels: GSSOC21, Level2
